/*
 * generated by Xtext 2.31.0
 */
package e4sm.de.metamodel.xtext.parser.antlr;

import com.google.inject.Inject;
import e4sm.de.metamodel.xtext.parser.antlr.internal.InternalE4smParser;
import e4sm.de.metamodel.xtext.services.E4smGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class E4smParser extends AbstractAntlrParser {

	@Inject
	private E4smGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalE4smParser createParser(XtextTokenStream stream) {
		return new InternalE4smParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public E4smGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(E4smGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
