/*
 * generated by Xtext 2.31.0
 */
package e4sm.de.metamodel.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class E4smAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("e4sm/de/metamodel/xtext/parser/antlr/internal/InternalE4sm.tokens");
	}
}
