/*
 * generated by Xtext 2.27.0
 */
package abcd.xy.metamodel.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ABcdAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("abcd/de/metamodel/xtext/parser/antlr/internal/InternalABcd.tokens");
	}
}
