/*
 * generated by Xtext 2.27.0
 */
package abcd.xy.metamodel.xtext.parser.antlr;

import com.google.inject.Inject;
import abcd.xy.metamodel.xtext.parser.antlr.internal.InternalABcdParser;
import abcd.xy.metamodel.xtext.services.ABcdGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ABcdParser extends AbstractAntlrParser {

	@Inject
	private ABcdGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalABcdParser createParser(XtextTokenStream stream) {
		return new InternalABcdParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ABcdGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ABcdGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
