/*
 * generated by Xtext 2.26.0
 */
package e4sm.de.metamodel.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class E4smStandaloneSetup extends E4smStandaloneSetupGenerated {

	public static void doSetup() {
		new E4smStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
