/*
 * generated by Xtext 2.26.0
 */
package e4sm.de.metamodel.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class E4smRuntimeModule extends AbstractE4smRuntimeModule {
}
