/*
 * generated by Xtext 2.27.0
 */
package abcd.xy.metamodel.xtext.ui.tests;

import com.google.inject.Injector;
import abcd.xy.metamodel.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ABcdUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("abcd.xy.metamodel.xtext.ABcd");
	}

}
