/*
 * generated by Xtext 2.26.0
 */
package abcd.xy.metamodel.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import abcd.xy.metamodel.xtext.ABcdRuntimeModule;
import abcd.xy.metamodel.xtext.ABcdStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ABcdIdeSetup extends ABcdStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ABcdRuntimeModule(), new ABcdIdeModule()));
	}
	
}
