/*
 * generated by Xtext 2.26.0
 */
package e4sm.de.metamodel.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class E4smUiModule extends AbstractE4smUiModule {

	public E4smUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
