/*
 * generated by Xtext 2.26.0
 */
package abcd.xy.metamodel.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ABcdStandaloneSetup extends ABcdStandaloneSetupGenerated {

	public static void doSetup() {
		new ABcdStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
