/*
 * generated by Xtext 2.26.0
 */
package abcd.xy.metamodel.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ABcdRuntimeModule extends AbstractABcdRuntimeModule {
}
