/*
 * generated by Xtext 2.31.0
 */
package e4sm.de.metamodel.xtext.ui.tests;

import com.google.inject.Injector;
import e4sm.de.metamodel.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class E4smUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("e4sm.de.metamodel.xtext.E4sm");
	}

}
