/*
 * generated by Xtext 2.26.0
 */
package abcd.xy.metamodel.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ABcdUiModule extends AbstractABcdUiModule {

	public ABcdUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
