/*
 * generated by Xtext 2.34.0
 */
package e4sm.de.metamodel.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractE4smScopeProvider extends DelegatingScopeProvider {
}
