/************************************************************

	MeasureObj_fsdf.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef _MEASURE_OBJ_fsdfHEADER
#define _MEASSURE_OBJ_fsdfHEADER

#include "gmnet.h"
#include "MeasureObj.h"

class MeasureObj_fsdf : public MeasureObj {
public:
	MeasureObj_fsdf(NetClass* net);
	~MeasureObj_fsdf();

	bool accumulative() {return true;}
	bool timeaverage() {return false;}
	double measure(double dt);
	void accum(const Binding *binding, double weight);
};

extern MeasureObj_fsdf* measure_fsdf;
#endif
