/************************************************************

	MeasureObj_Binary__precision.cpp  -  generated by CodeGenerator r$Rev$

************************************************************/

#include "Token_int.h"
#include "Token_bool.h"
#include "Token_real.h"
#include "Token_string.h"
#include "Token_DateTime.h"
#include "Token_Data.h"
#include "MeasureObj_C1__in__use.h"
#include "MeasureObj_Binary__accuracy.h"
#include "MeasureObj_Binary__specificity.h"
#include "MeasureObj_Binary__recall.h"
#include "MeasureObj_Binary__precision.h"
#include "MeasureObj_Binary__f1Score.h"
#include "MeasureObj_fsdf.h"
#include "MeasureObj_PlaceTP.h"

MeasureObj_Binary__precision* measure_Binary__precision;

MeasureObj_Binary__precision::MeasureObj_Binary__precision(NetClass* net) : MeasureObj("Binary_precision", net, false)
{
}

double MeasureObj_Binary__precision::measure(double dt=-1)
{
	// Orig Expression: #Binary_tp / (0.00000001 + #Binary_tp + #Binary_fp)
	// C++  Expression: #P000051/ ( 1.0E-8+#P000052+#P000053 ) 
	Place *P000051 = net->getPlace("Binary_tp");
	Place *P000052 = net->getPlace("Binary_tp");
	Place *P000053 = net->getPlace("Binary_fp");

	double rate = (P000051->getMarkingSize()/ ( 1.0E-8+P000052->getMarkingSize()+P000053->getMarkingSize() ) );

	return rate;
}

void MeasureObj_Binary__precision::accum(const Binding *binding, double weight) {}
MeasureObj_Binary__precision::~MeasureObj_Binary__precision()
{
}

