/************************************************************

	MeasureObj_PlaceTP.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef _MEASURE_OBJ_PlaceTPHEADER
#define _MEASSURE_OBJ_PlaceTPHEADER

#include "gmnet.h"
#include "MeasureObj.h"

class MeasureObj_PlaceTP : public MeasureObj {
public:
	MeasureObj_PlaceTP(NetClass* net);
	~MeasureObj_PlaceTP();

	bool accumulative() {return false;}
	bool timeaverage() {return false;}
	double measure(double dt);
	void accum(const Binding *binding, double weight);
};

extern MeasureObj_PlaceTP* measure_PlaceTP;
#endif
