/************************************************************

	Transition_Act1__execution.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef TRANSITION_Act1__execution_H_FILE
#define TRANSITION_Act1__execution_H_FILE

#include "MSVCC.h"
#include "Transition.h"
#include "Token_Data.h"
#include "Token_int.h"


class Transition_Act1__execution : public Transition {
public:
	Transition_Act1__execution(int uniqueid, const char* name, NetClass* net, PlaceIdentMap places, string pagePath="", double firingWeight=0, int priority=0, bool exp=true, bool takeFirst=false, bool hasLocalGuard=false, bool isInfinite=false);
	~Transition_Act1__execution();
protected:
	//ingoing places for this transition
	Place& x_Place;
	Place& pool_Place;

	//outgoing places for this transition
	Place& nona1_Place;

	void initGlobalGuards();
	bool globalGuard();
	void moveTokens(TokenList &binding);
	TempBindingList* generateBindingList();
	bool hasTimeguard() const;
	Seconds_T Timeguard(const DateTime& now);
	Seconds_T getFiringDelay(TokenList &binding) const;
	double display(TokenList &binding);
	void log(TokenList &binding);
};

#endif
