/************************************************************

	MeasureObj_Act1Ready.cpp  -  generated by CodeGenerator r$Rev$

************************************************************/

#include "Token_int.h"
#include "Token_bool.h"
#include "Token_real.h"
#include "Token_string.h"
#include "Token_DateTime.h"
#include "Token_Data.h"
#include "MeasureObj_C1__in__use.h"
#include "MeasureObj_AReady.h"
#include "MeasureObj_Act1Ready.h"
#include "MeasureObj_Act2Ready.h"
#include "MeasureObj_A3Ready.h"
#include "MeasureObj_Binary__accuracy.h"
#include "MeasureObj_Binary__specificity.h"
#include "MeasureObj_Binary__recall.h"
#include "MeasureObj_Binary__precision.h"
#include "MeasureObj_Binary__f1Score.h"

MeasureObj_Act1Ready* measure_Act1Ready;

MeasureObj_Act1Ready::MeasureObj_Act1Ready(NetClass* net) : MeasureObj("Act1Ready", net, true)
{
	firstTime = lastTime = 0;
	value = 0;
}

double MeasureObj_Act1Ready::measure(double dt=-1)
{
	return value;
}

void MeasureObj_Act1Ready::accum(const Binding *binding, double weight) {
	const DateTime &t = binding->getTime();
	double dt = t.FullDateTime() - lastTime;
	lastTime = t.FullDateTime();

	// Orig Expression: #Act1_executed
	// C++  Expression: #P000029
	Place *P000029 = net->getPlace("Act1_executed");

	const Transition *trans = binding->getBoundTransition();
	const TokenList *tokens = binding->getBoundTokens();

	double rate = (P000029->getMarkingSize());

	value += weight * dt * rate;
}

MeasureObj_Act1Ready::~MeasureObj_Act1Ready()
{
}

