/************************************************************

	MeasureObj_Act2Ready.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef _MEASURE_OBJ_Act2ReadyHEADER
#define _MEASSURE_OBJ_Act2ReadyHEADER

#include "gmnet.h"
#include "MeasureObj.h"

class MeasureObj_Act2Ready : public MeasureObj {
public:
	MeasureObj_Act2Ready(NetClass* net);
	~MeasureObj_Act2Ready();

	bool accumulative() {return true;}
	bool timeaverage() {return false;}
	double measure(double dt);
	void accum(const Binding *binding, double weight);
};

extern MeasureObj_Act2Ready* measure_Act2Ready;
#endif
