/************************************************************

	MeasureObj_Binary__specificity.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef _MEASURE_OBJ_Binary__specificityHEADER
#define _MEASSURE_OBJ_Binary__specificityHEADER

#include "gmnet.h"
#include "MeasureObj.h"

class MeasureObj_Binary__specificity : public MeasureObj {
public:
	MeasureObj_Binary__specificity(NetClass* net);
	~MeasureObj_Binary__specificity();

	bool accumulative() {return false;}
	bool timeaverage() {return false;}
	double measure(double dt);
	void accum(const Binding *binding, double weight);
};

extern MeasureObj_Binary__specificity* measure_Binary__specificity;
#endif
