/************************************************************

	MeasureObj_AReady.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef _MEASURE_OBJ_AReadyHEADER
#define _MEASSURE_OBJ_AReadyHEADER

#include "gmnet.h"
#include "MeasureObj.h"

class MeasureObj_AReady : public MeasureObj {
public:
	MeasureObj_AReady(NetClass* net);
	~MeasureObj_AReady();

	bool accumulative() {return true;}
	bool timeaverage() {return false;}
	double measure(double dt);
	void accum(const Binding *binding, double weight);
};

extern MeasureObj_AReady* measure_AReady;
#endif
