/************************************************************

	MeasureObj_Act1Ready.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef _MEASURE_OBJ_Act1ReadyHEADER
#define _MEASSURE_OBJ_Act1ReadyHEADER

#include "gmnet.h"
#include "MeasureObj.h"

class MeasureObj_Act1Ready : public MeasureObj {
public:
	MeasureObj_Act1Ready(NetClass* net);
	~MeasureObj_Act1Ready();

	bool accumulative() {return true;}
	bool timeaverage() {return false;}
	double measure(double dt);
	void accum(const Binding *binding, double weight);
};

extern MeasureObj_Act1Ready* measure_Act1Ready;
#endif
