/************************************************************

	MeasureObj_Binary__f1Score.cpp  -  generated by CodeGenerator r$Rev$

************************************************************/

#include "Token_int.h"
#include "Token_bool.h"
#include "Token_real.h"
#include "Token_string.h"
#include "Token_DateTime.h"
#include "Token_Data.h"
#include "MeasureObj_C1__in__use.h"
#include "MeasureObj_AReady.h"
#include "MeasureObj_Act1Ready.h"
#include "MeasureObj_Act2Ready.h"
#include "MeasureObj_A3Ready.h"
#include "MeasureObj_Binary__accuracy.h"
#include "MeasureObj_Binary__specificity.h"
#include "MeasureObj_Binary__recall.h"
#include "MeasureObj_Binary__precision.h"
#include "MeasureObj_Binary__f1Score.h"

MeasureObj_Binary__f1Score* measure_Binary__f1Score;

MeasureObj_Binary__f1Score::MeasureObj_Binary__f1Score(NetClass* net) : MeasureObj("Binary_f1Score", net, false)
{
}

double MeasureObj_Binary__f1Score::measure(double dt=-1)
{
	// Orig Expression: #Binary_tp / (0.00000001 + #Binary_tp +(#Binary_fn + #Binary_fp)/2.0)
	// C++  Expression: #P000068/ ( 1.0E-8+#P000069+ ( #P000070+#P000071 ) /2.0 ) 
	Place *P000068 = net->getPlace("Binary_tp");
	Place *P000069 = net->getPlace("Binary_tp");
	Place *P000070 = net->getPlace("Binary_fn");
	Place *P000071 = net->getPlace("Binary_fp");

	double rate = (P000068->getMarkingSize()/ ( 1.0E-8+P000069->getMarkingSize()+ ( P000070->getMarkingSize()+P000071->getMarkingSize() ) /2.0 ) );

	return rate;
}

void MeasureObj_Binary__f1Score::accum(const Binding *binding, double weight) {}
MeasureObj_Binary__f1Score::~MeasureObj_Binary__f1Score()
{
}

