/************************************************************

	MeasureObj_Binary__accuracy.cpp  -  generated by CodeGenerator r$Rev$

************************************************************/

#include "Token_int.h"
#include "Token_bool.h"
#include "Token_real.h"
#include "Token_string.h"
#include "Token_DateTime.h"
#include "Token_Data.h"
#include "MeasureObj_C1__in__use.h"
#include "MeasureObj_AReady.h"
#include "MeasureObj_Act1Ready.h"
#include "MeasureObj_Act2Ready.h"
#include "MeasureObj_A3Ready.h"
#include "MeasureObj_Binary__accuracy.h"
#include "MeasureObj_Binary__specificity.h"
#include "MeasureObj_Binary__recall.h"
#include "MeasureObj_Binary__precision.h"
#include "MeasureObj_Binary__f1Score.h"

MeasureObj_Binary__accuracy* measure_Binary__accuracy;

MeasureObj_Binary__accuracy::MeasureObj_Binary__accuracy(NetClass* net) : MeasureObj("Binary_accuracy", net, false)
{
}

double MeasureObj_Binary__accuracy::measure(double dt=-1)
{
	// Orig Expression: (#Binary_tp+ #Binary_tn) / (0.00000001 + #Binary_tp + #Binary_tn + #Binary_fp + #Binary_fn)
	// C++  Expression:  ( #P000040+#P000041 ) / ( 1.0E-8+#P000042+#P000043+#P000044+#P000045 ) 
	Place *P000040 = net->getPlace("Binary_tp");
	Place *P000041 = net->getPlace("Binary_tn");
	Place *P000042 = net->getPlace("Binary_tp");
	Place *P000043 = net->getPlace("Binary_tn");
	Place *P000044 = net->getPlace("Binary_fp");
	Place *P000045 = net->getPlace("Binary_fn");

	double rate = ( ( P000040->getMarkingSize()+P000041->getMarkingSize() ) / ( 1.0E-8+P000042->getMarkingSize()+P000043->getMarkingSize()+P000044->getMarkingSize()+P000045->getMarkingSize() ) );

	return rate;
}

void MeasureObj_Binary__accuracy::accum(const Binding *binding, double weight) {}
MeasureObj_Binary__accuracy::~MeasureObj_Binary__accuracy()
{
}

