/************************************************************

	MeasureObj_Binary__recall.cpp  -  generated by CodeGenerator r$Rev$

************************************************************/

#include "Token_int.h"
#include "Token_bool.h"
#include "Token_real.h"
#include "Token_string.h"
#include "Token_DateTime.h"
#include "Token_Data.h"
#include "MeasureObj_C1__in__use.h"
#include "MeasureObj_AReady.h"
#include "MeasureObj_Act1Ready.h"
#include "MeasureObj_Act2Ready.h"
#include "MeasureObj_A3Ready.h"
#include "MeasureObj_Binary__accuracy.h"
#include "MeasureObj_Binary__specificity.h"
#include "MeasureObj_Binary__recall.h"
#include "MeasureObj_Binary__precision.h"
#include "MeasureObj_Binary__f1Score.h"

MeasureObj_Binary__recall* measure_Binary__recall;

MeasureObj_Binary__recall::MeasureObj_Binary__recall(NetClass* net) : MeasureObj("Binary_recall", net, false)
{
}

double MeasureObj_Binary__recall::measure(double dt=-1)
{
	// Orig Expression: #Binary_tp / (0.00000001 + #Binary_tp + #Binary_fn)
	// C++  Expression: #P000055/ ( 1.0E-8+#P000056+#P000057 ) 
	Place *P000055 = net->getPlace("Binary_tp");
	Place *P000056 = net->getPlace("Binary_tp");
	Place *P000057 = net->getPlace("Binary_fn");

	double rate = (P000055->getMarkingSize()/ ( 1.0E-8+P000056->getMarkingSize()+P000057->getMarkingSize() ) );

	return rate;
}

void MeasureObj_Binary__recall::accum(const Binding *binding, double weight) {}
MeasureObj_Binary__recall::~MeasureObj_Binary__recall()
{
}

