/************************************************************

	MeasureObj_A3Ready.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef _MEASURE_OBJ_A3ReadyHEADER
#define _MEASSURE_OBJ_A3ReadyHEADER

#include "gmnet.h"
#include "MeasureObj.h"

class MeasureObj_A3Ready : public MeasureObj {
public:
	MeasureObj_A3Ready(NetClass* net);
	~MeasureObj_A3Ready();

	bool accumulative() {return true;}
	bool timeaverage() {return false;}
	double measure(double dt);
	void accum(const Binding *binding, double weight);
};

extern MeasureObj_A3Ready* measure_A3Ready;
#endif
