/************************************************************

	Transition_Binary____cf__tn.h  -  generated by CodeGenerator r$Rev$

************************************************************/

#ifndef TRANSITION_Binary____cf__tn_H_FILE
#define TRANSITION_Binary____cf__tn_H_FILE

#include "MSVCC.h"
#include "Transition.h"
#include "Token_Data.h"
#include "Token_int.h"


class Transition_Binary____cf__tn : public Transition {
public:
	Transition_Binary____cf__tn(int uniqueid, const char* name, NetClass* net, PlaceIdentMap places, string pagePath="", double firingWeight=0, int priority=0, bool exp=false, bool takeFirst=false, bool hasLocalGuard=false, bool isInfinite=false);
	~Transition_Binary____cf__tn();
protected:
	//ingoing places for this transition
	Place& x_Place;

	//outgoing places for this transition
	Place& nona1_Place;

	void initGlobalGuards();
	bool globalGuard();
	void moveTokens(TokenList &binding);
	TempBindingList* generateBindingList();
	bool hasTimeguard() const;
	Seconds_T Timeguard(const DateTime& now);
	Seconds_T getFiringDelay(TokenList &binding) const;
	double display(TokenList &binding);
	void log(TokenList &binding);
};

#endif
