/************************************************************

	Transition_A3__execution.cpp  -  generated by CodeGenerator r$Rev$

************************************************************/

#include "Transition_A3__execution.h"

#include "MeasureObj_C1__in__use.h"
#include "MeasureObj_AReady.h"
#include "MeasureObj_Act1Ready.h"
#include "MeasureObj_Act2Ready.h"
#include "MeasureObj_A3Ready.h"
#include "MeasureObj_Binary__accuracy.h"
#include "MeasureObj_Binary__specificity.h"
#include "MeasureObj_Binary__recall.h"
#include "MeasureObj_Binary__precision.h"
#include "MeasureObj_Binary__f1Score.h"

Transition_A3__execution::Transition_A3__execution(int uniqueid, const char* name, NetClass* net, PlaceIdentMap places, string pagePath, double firingWeight, int priority, bool exp, bool takeFirst, bool isInfinite, bool hasLocalGuard) :
	Transition(uniqueid, name, net, places, pagePath, firingWeight, priority, exp, takeFirst, isInfinite, hasLocalGuard)
,
	x_Place ( *(net->getPlace( &places, "A3_in_1"))),
	pool_Place ( *(net->getPlace( &places, "P_thread_pool"))),
	nona1_Place ( *(net->getPlace( &places, "A3_executed")))
{
}

Transition_A3__execution::~Transition_A3__execution()
{
}

bool Transition_A3__execution::globalGuard()
{
	return true;
}
void Transition_A3__execution::initGlobalGuards()
{
}

void Transition_A3__execution::moveTokens(TokenList &binding)
{
	TokenList::iterator binding_it = binding.begin();

	SMARTPTR(Token_Data) token_x = UPCAST_MACRO(Token_Data)(*binding_it ++);
	x_Place.removeToken(token_x);
	SMARTPTR(Token_int) token_pool = UPCAST_MACRO(Token_int)(*binding_it ++);
	pool_Place.removeToken(token_pool);

	{
		// Handle token 1 of 1

		// Transfering Token: 1'x
		{
			nona1_Place.addToken(token_x);
		}
	}
}

TempBindingList* Transition_A3__execution::generateBindingList()
{
	TokenList* tok;
	TempBindingList* tempBindings =  new TempBindingList();

	const TokenList &x_tokenList = getPlaceMarking(x_Place);
	TokenList::const_iterator x_iterator;
	const TokenList &pool_tokenList = getPlaceMarking(pool_Place);
	TokenList::const_iterator pool_iterator;

	for (x_iterator=x_tokenList.begin(); x_iterator!=x_tokenList.end(); ++x_iterator) {
		for (pool_iterator=pool_tokenList.begin(); pool_iterator!=pool_tokenList.end(); ++pool_iterator) {
			SMARTPTR(Token_Data) token_x = UPCAST_MACRO(Token_Data)(*x_iterator);
			SMARTPTR(Token_int) token_pool = UPCAST_MACRO(Token_int)(*pool_iterator);
			
			// Check nulls 
			if (token_x == 0) {
				continue;
			}
			if (token_pool == 0) {
				continue;
			}
			
			{
				
				// Check nulls 
				
			}

			// All local guards passed:
			tok = new TokenList();
			tok->push_back(UPCAST_MACRO(Token_Data)(*x_iterator));
			tok->push_back(UPCAST_MACRO(Token_int)(*pool_iterator));
			tempBindings->push_back(tok);
			return tempBindings;
		}
	}
	return tempBindings;
}

void Transition_A3__execution::log(TokenList &binding)
{
}

double Transition_A3__execution::display(TokenList &binding)
{
	return 0.0;
}

Seconds_T Transition_A3__execution::getFiringDelay(TokenList &binding) const
{
	// Orig Expression: Exp(1.0)
	// C++  Expression: 1.0

	TokenList::iterator binding_it = binding.begin();

	SMARTPTR(Token_Data) token_x = UPCAST_MACRO(Token_Data)(*binding_it ++);
	SMARTPTR(Token_int) token_pool = UPCAST_MACRO(Token_int)(*binding_it ++);
	return delay.Exp(1.0);
}

bool Transition_A3__execution::hasTimeguard() const
{
	return false;
}

Seconds_T Transition_A3__execution::Timeguard(const DateTime& now)
{
	return 0.0;
}

