<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://de.tu-ilmenau/e4sm/core/1.0.0" nsPrefix="core">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"/>
  <eAnnotations source="http://www.eclipse.org/edapt">
    <details key="historyURI" value="e4sm.history"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Float" instanceClassName="float"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="double"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Long" instanceClassName="long"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Short" instanceClassName="short"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Character" instanceClassName="char"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Byte" instanceClassName="byte"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.time.LocalDate"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Timestamp" instanceClassName="java.time.LocalDateTime"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Time" instanceClassName="java.time.LocalTime"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An Element which has a name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A model element"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralSpecification" abstract="true"
      eSuperTypes="#//ValueSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralNull" eSuperTypes="#//LiteralSpecification"/>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralString" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#//LiteralSpecification">
    <eOperations name="getTangibleChild" eType="ecore:EClass execution.ecore#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Integer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralBoolean" eSuperTypes="#//LiteralSpecification">
    <eOperations name="getValue" eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralFloat" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Float"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralDouble" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Double"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralLong" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Long"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralShort" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Short"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralByte" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Byte"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralCharacter" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Character"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralDate" eSuperTypes="#//LiteralSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Date"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true"
      eSuperTypes="#//TypedElement execution.ecore#//Expression">
    <eOperations name="booleanValue" eType="#//Boolean"/>
    <eOperations name="integerValue" eType="#//Integer"/>
    <eOperations name="isComputable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getTangibleChild" eType="ecore:EClass execution.ecore#//Expression"/>
    <eOperations name="getActualParent" eType="ecore:EClass execution.ecore#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnitOfMeasurement">
    <eLiterals name="cm" value="9"/>
    <eLiterals name="m" value="1"/>
    <eLiterals name="mm" value="2"/>
    <eLiterals name="percentage" value="3"/>
    <eLiterals name="s" value="4"/>
    <eLiterals name="ms" value="5"/>
    <eLiterals name="minutes" value="6"/>
    <eLiterals name="hours" value="7"/>
    <eLiterals name="mbps" value="8"/>
    <eLiterals name="none"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variant" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterizableElement" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="ecore:EClass analysis.ecore#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeSpecification" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AttributeSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//TypeSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSpecification" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="array" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerAttribute" eSuperTypes="#//AttributeSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleAttribute" eSuperTypes="#//AttributeSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringAttribute" eSuperTypes="#//AttributeSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanAttribute" eSuperTypes="#//AttributeSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassAttribute" eSuperTypes="#//AttributeSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//TypeSpecification"/>
  </eClassifiers>
</ecore:EPackage>
