<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="e4sm" nsURI="http://de.tu-ilmenau/e4sm/1.0.0" nsPrefix="e4sm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//core/NamedElement #//analysis/ParameterizableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Generic component, which should be used to temporally specify an element before deciding how it will be realised.&#xD;&#xA;&#xD;&#xA;Constraints:&#xD;&#xA;- C1: no loops allowed between the component container (Package) and component &quot;specifiedInPackage&quot;&#xD;&#xA;- C2: components->size()>0, then specifiedInPackage=null - If the component contains other components, it can't be specified in a package."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ComponentC1 ComponentC2 ComponentC3"/>
    </eAnnotations>
    <eOperations name="computeMainResponsible" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of components contained by this component"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pins" upperBound="-1" eType="#//Pin"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of pins (input and output pins) which are placed on the border of this component."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainResponsible" eType="#//Person"
        eOpposite="#//Person/responsibleForComponents">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A person who is responsible for realising and/or designing this component"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiedInPackage" eType="#//Package"
        eOpposite="#//Package/specifiesComponent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A component may get specified further in a package&#xD;&#xA;Constraints:&#xD;&#xA;- C0: no loops allowed (implemented in Component)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeSpecification" eType="#//CodeSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineLearningComponent" eSuperTypes="#//SoftwareComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A software component which returns results based on a machine learning method estimate (e.g. classification...)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" eSuperTypes="#//analysis/ParameterizableElement #//core/NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A connector connects one source to one target component.&#xD;&#xA;Constraints:&#xD;&#xA;- C1: A connector shall not connect two pins of the same component directly (loop/short circuit)"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ConnectorC1"/>
    </eAnnotations>
    <eOperations name="computeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Pin" eOpposite="#//Pin/outgoingConnectors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Pin" eOpposite="#//Pin/incomingConnectors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalConnector" eSuperTypes="#//Connector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A phyisical connector is a connector which links 2 physical components.&#xD;&#xA;Constraints:&#xD;&#xA;- C1: A Physical Connector shall only connect Physical Components.&#xD;&#xA;- C2: An output pin shall only be connected to an input pin.&#xD;&#xA;- C3: An input pin shall only be connected to an output pin."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PhysicalConnectorC1 PhysicalConnectorC2 PhysicalConnectorC3"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSpeed" eType="#//Connectionspeed"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSpeed" eType="#//Connectionspeed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Connectionspeed" instanceTypeName="newDataType1"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalComponent" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A physical component is a generic tangible component which will be realised/is already available as hardware"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareComponent" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A software component is a generic component which will be realised/is already available digitally"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SoftwareComponentC1"/>
    </eAnnotations>
    <eOperations name="isParallel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputUncertainty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronous" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If synchronous, the execution is blocked on the current component until it provides a result. If the component is asynchronous, the execution continues immediatly and the results are provided in other ways (e.g. written out somewhere, with an event system, with promise systems, by polling...)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfServers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of computational units. If one, the execution is syncronous. If > 1, the execution will be parallel."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalConnector" eSuperTypes="#//Connector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A logical connector connects 2 software components or 1 software and one physical component"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Heuristic" eSuperTypes="#//SoftwareComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A heuristic is a software component which may provide a wrong/non-optimal result for certain inputs"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//SoftwareComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A function is a in-house programmed software which is considered to be safe (apart from a low output uncertainty due to possible bugs)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDependency" eSuperTypes="#//SoftwareComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An external dependency is a function which is offered by a third party and can't be controlled."/>
    </eAnnotations>
    <eOperations name="computeMainResponsible" eType="#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//core/NamedElement #//analysis/ParameterizableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A package contains a set of Components and their connections.&#xD;&#xA;Constraints:&#xD;&#xA;- C1: all owned packages must have &quot;specifiesComponent&quot; set to a component owned by this package."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PackageC1"/>
    </eAnnotations>
    <eOperations name="getAllComponents" upperBound="-1" eType="#//Component">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns all components directly contained by this package, including those inside sectors."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of components contained in this package"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareComponents" upperBound="-1"
        eType="#//SoftwareComponent" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A subset of components only containing software components"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="physicalComponents" upperBound="-1"
        eType="#//PhysicalComponent" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A subset of components only containing physical components"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connector" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of connectors contained in this package"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectors" upperBound="-1"
        eType="#//Sector" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of sectors contained in this package"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainResponsible" eType="#//Person">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The main responsible for the realisation of this package"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A package may contains subpackages, which specify one of the components owned by this package"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiesComponent" eType="#//Component"
        eOpposite="#//Component/specifiedInPackage">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This package is the detailed representation of another component (optional)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//core/NamedElement #//analysis/ParameterizableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The root element of the E4SM Model"/>
    </eAnnotations>
    <eOperations name="isPersonPicturePathValid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of packages contained by this model"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of actors contained by this model"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personsPicturesPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A workspace path pointing to a folder containing person's pictures. It must start and and with a /. Example: /My Model/img/"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1"
        eType="#//analysis/Variant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//core/NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An Entity which interfaces with the system"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Human" eSuperTypes="#//Actor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A human actor"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Robot" eSuperTypes="#//Actor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A robot actor"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sector" eSuperTypes="#//core/NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A collection of physical components that either logically or phisically belongs together"/>
    </eAnnotations>
    <eOperations name="getAllComponents" upperBound="-1" eType="#//Component">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns all components directly contained by this package, including those inside sectors."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of references to components which are contained in this sector. Only Physical Components should be allowed."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sectors" upperBound="-1"
        eType="#//Sector" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of sectors contained by this sector"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//PhysicalComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A physical component which transforms a physical signal into a digital one&#xD;&#xA;Constraints:&#xD;&#xA;- C1: A sensor shall not have input pins"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SensorC1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeFunction" lowerBound="1"
        eType="#//TimeFunction" defaultValueLiteral="EXP(1.0)"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//PhysicalComponent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A physical component which transforms a digital signal into a physical one&#xD;&#xA;Constraints:&#xD;&#xA;- C1: An actuator shall not have output pins"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ActuatorC1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true" eSuperTypes="#//analysis/ParameterizableElement #//core/TypedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An interface to and from a component"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PinC1"/>
    </eAnnotations>
    <eOperations name="computeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnectors" upperBound="-1"
        eType="#//Connector" eOpposite="#//Connector/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnectors" upperBound="-1"
        eType="#//Connector" eOpposite="#//Connector/target"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gatewayPin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stream" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="raceSemantic" unique="false"
        eType="#//RaceSemantic" defaultValueLiteral="MERGE_AND_DUPLICATE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When multiple connectors are connected to a pin, the race semantic specifies how the data gets sent forward."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPin" eSuperTypes="#//Pin">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An interface which delivers data inside a component"/>
    </eAnnotations>
    <eOperations name="computeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queueType" eType="#//QueueType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When multiple data reaches this pin, the Queue type decides how they will be processed"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPin" eSuperTypes="#//Pin">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An interface which sends data outside of a component"/>
    </eAnnotations>
    <eOperations name="computeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//Human">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A person, which may be responsible for the realisation of a certain number of components"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The surname of the person"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="department" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the department"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleForComponents"
        upperBound="-1" eType="#//Component" eOpposite="#//Component/mainResponsible">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A list of elements which lay under this person's responsibility"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pictureFileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The file name, including the extension of this person's picture. The folder where it is located must be specified in the model element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JSON" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurementUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unitConversion" eType="#//UnitConversion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleUnit" eSuperTypes="#//MeasurementUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedUnit" eSuperTypes="#//MeasurementUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitConversion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceUnit" lowerBound="1"
        eType="#//MeasurementUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConversionByPrefix" eSuperTypes="#//UnitConversion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prefix" lowerBound="1"
        eType="#//UnitPrefix"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConversionByConvention" eSuperTypes="#//UnitConversion"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitPrefix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueueType">
    <eLiterals name="FIFO">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="First in, first out"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LIFO" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Last in, Last out (stack)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="RANDOM" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An element of the queue is picked randomly"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LATEST_ONLY" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="There is no queue, only the latest received element remain stored. Once consumed, the pin does not have any other data available until it receives a new one."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="STORE" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The data remain stored in the pin. If new data arrives, it replace the currently stored data."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RaceSemantic">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="When multiple connectors are connected to a pin, the race semantic specifies how the data gets sent forward."/>
    </eAnnotations>
    <eLiterals name="FCFS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FCFS - First come, first served.&#xD;&#xA;In this mode, the output is consumed by one of the following components."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DUPLICATE" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="In this mode, the data is duplicated and made available to each and every following components. This value is only valid for pins with multiple outgoing connectors."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MERGE" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="In this mode, a value is required from each incoming connector, before the execution can continue with one single token. This value is only valid on pins with multiple incoming connectors."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MERGE_AND_DUPLICATE" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="In this mode, a value is required from each incoming connector, before the execution can continue with one single token, which will be duplicated on all outgoing edges. &#xD;&#xA;This value is only valid on pins with multiple incoming and outgoing connectors."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TimeFunction" instanceClassName="java.lang.String">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A string containing a valid TimeFunction, e.g. EXP(1.0)"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="TimeFunctionIsValid"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CodeSpecification" instanceClassName="java.lang.String">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="CodeSpecificationIsValid"/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="core" nsURI="http://de.tu-ilmenau/e4sm/core/1.0.0" nsPrefix="core">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="int"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Float" instanceClassName="float"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="double"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Long" instanceClassName="long"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Short" instanceClassName="short"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Character" instanceClassName="char"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Byte" instanceClassName="byte"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.time.LocalDate"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Timestamp" instanceClassName="java.time.LocalDateTime"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Time" instanceClassName="java.time.LocalTime"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//core/Element">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An Element which has a name"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The name of the element"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A model element"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralSpecification" abstract="true"
        eSuperTypes="#//core/ValueSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralNull" eSuperTypes="#//core/LiteralSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralString" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralInteger" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralBoolean" eSuperTypes="#//core/LiteralSpecification">
      <eOperations name="getValue" eType="#//core/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralFloat" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Float"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralDouble" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Double"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralLong" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Long"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralShort" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Short"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralByte" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Byte"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralCharacter" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Character"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralDate" eSuperTypes="#//core/LiteralSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//core/Date"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true"
        eSuperTypes="#//core/TypedElement">
      <eOperations name="booleanValue" eType="#//core/Boolean"/>
      <eOperations name="integerValue" eType="#//core/Integer"/>
      <eOperations name="isComputable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UnitOfMeasurement">
      <eLiterals name="cm" value="9"/>
      <eLiterals name="m" value="1"/>
      <eLiterals name="mm" value="2"/>
      <eLiterals name="percentage" value="3"/>
      <eLiterals name="s" value="4"/>
      <eLiterals name="ms" value="5"/>
      <eLiterals name="minutes" value="6"/>
      <eLiterals name="hours" value="7"/>
      <eLiterals name="mbps" value="8"/>
      <eLiterals name="none"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="analysis" nsURI="http://de.tu-ilmenau/e4sm/analysis/1.0.0" nsPrefix="analysis">
    <eClassifiers xsi:type="ecore:EClass" name="AnalysisManager">
      <eOperations name="start" eType="#//analysis/results/AnalysisExecution">
        <eParameters name="a" upperBound="-1" eType="#//analysis/Analysis"/>
      </eOperations>
      <eOperations name="storeResult" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="res" eType="#//analysis/results/AnalysisExecution"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnalysisDefinition" eSuperTypes="#//core/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDefinitions"
          upperBound="-1" eType="#//analysis/ParameterDefinition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="analysis" lowerBound="1"
          eType="#//analysis/Analysis" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterDefinition" eSuperTypes="#//core/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//analysis/Parameter" eOpposite="#//analysis/Parameter/parameterDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//core/UnitOfMeasurement"
          defaultValueLiteral="none"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mustBeDefinedOn" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="canBeDefinedOn" upperBound="-1"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="shallNotBeDefinedOn"
          upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//core/ValueSpecification"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//core/Element">
      <eOperations name="isValid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterDefinition"
          lowerBound="1" eType="#//analysis/ParameterDefinition" eOpposite="#//analysis/ParameterDefinition/parameters"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="appliesOnlyOnVariants"
          upperBound="-1" eType="#//analysis/Variant"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="doesNotApplyOnVariants"
          upperBound="-1" eType="#//analysis/Variant"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" eType="#//core/ValueSpecification"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentValue" eType="#//core/ValueSpecification"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterizableElement" abstract="true"
        interface="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//analysis/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Analysis" abstract="true">
      <eOperations name="exec"/>
      <eOperations name="init" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="postExecution"/>
      <eOperations name="run" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModelAnalysis" abstract="true" eSuperTypes="#//analysis/Analysis"/>
    <eClassifiers xsi:type="ecore:EClass" name="GraphAnalysis" abstract="true" eSuperTypes="#//analysis/Analysis">
      <eTypeParameters name="C"/>
      <eOperations name="initGraph"/>
      <eOperations name="init" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph">
        <eGenericType eClassifier="#//guava/Graph">
          <eTypeArguments eTypeParameter="#//analysis/GraphAnalysis/C"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MemoryLessGraphAnalysis">
      <eTypeParameters name="C"/>
      <eGenericSuperTypes eClassifier="#//analysis/GraphAnalysis">
        <eTypeArguments eTypeParameter="#//analysis/MemoryLessGraphAnalysis/C"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EntireGraphAnalysis">
      <eTypeParameters name="C"/>
      <eGenericSuperTypes eClassifier="#//analysis/GraphAnalysis">
        <eTypeArguments eTypeParameter="#//analysis/EntireGraphAnalysis/C"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PackageAnalysis" eSuperTypes="#//analysis/Analysis"/>
    <eClassifiers xsi:type="ecore:EClass" name="PreviousNodeGraphAnalysis">
      <eTypeParameters name="C"/>
      <eGenericSuperTypes eClassifier="#//analysis/GraphAnalysis">
        <eTypeArguments eTypeParameter="#//analysis/PreviousNodeGraphAnalysis/C"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variant" eSuperTypes="#//core/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkGenerator">
      <eOperations name="generateNetwork">
        <eGenericType eClassifier="#//guava/ImmutableNetwork">
          <eTypeArguments eClassifier="#//Component"/>
          <eTypeArguments eClassifier="#//Connector"/>
        </eGenericType>
        <eParameters name="m" eType="#//Model"/>
      </eOperations>
      <eOperations name="generateNetwork">
        <eGenericType eClassifier="#//guava/ImmutableNetwork">
          <eTypeArguments eClassifier="#//Component"/>
          <eTypeArguments eClassifier="#//Connector"/>
        </eGenericType>
        <eParameters name="p" eType="#//Package"/>
      </eOperations>
    </eClassifiers>
    <eSubpackages name="results" nsURI="http://de.tu-ilmenau/e4sm/analysis/results/1.0.0"
        nsPrefix="results">
      <eClassifiers xsi:type="ecore:EClass" name="AnalysisResult" abstract="true"
          eSuperTypes="#//core/NamedElement"/>
      <eClassifiers xsi:type="ecore:EClass" name="Diagram" abstract="true" eSuperTypes="#//analysis/results/AnalysisResult"/>
      <eClassifiers xsi:type="ecore:EClass" name="Plot" abstract="true" eSuperTypes="#//analysis/results/Diagram"/>
      <eClassifiers xsi:type="ecore:EClass" name="TwoDimensionalPlot" eSuperTypes="#//analysis/results/Plot">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="xLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="yLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ThreeDimensionalPlot" eSuperTypes="#//analysis/results/TwoDimensionalPlot">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="zLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ScalarValue" eSuperTypes="#//analysis/results/Data">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true" eSuperTypes="#//analysis/results/AnalysisResult"/>
      <eClassifiers xsi:type="ecore:EClass" name="AnalysisExecution">
        <eStructuralFeatures xsi:type="ecore:EReference" name="analysisResults" upperBound="-1"
            eType="#//analysis/results/AnalysisResult" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="started" eType="#//core/Timestamp"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="finished" eType="#//core/Timestamp"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="analysis" eType="#//analysis/Analysis"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="runOnModel" eType="#//Model"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="guava" nsURI="https://guava.dev/releases/30.1" nsPrefix="guava">
    <eClassifiers xsi:type="ecore:EClass" name="Graph" instanceClassName="com.google.common.graph.Graph"
        abstract="true" interface="true">
      <eTypeParameters name="N"/>
      <eOperations name="isDirected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="inDegree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eParameters name="node">
          <eGenericType eTypeParameter="#//guava/Graph/N"/>
        </eParameters>
      </eOperations>
      <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eOperations name="allowsSelfLoops" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eGenericSuperTypes eClassifier="#//guava/PredecessorsFunction">
        <eTypeArguments eTypeParameter="#//guava/Graph/N"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//guava/SuccessorsFunction">
        <eTypeArguments eTypeParameter="#//guava/Graph/N"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractGraph" instanceClassName="com.google.common.graph.AbstractGraph"
        abstract="true" interface="true" eSuperTypes="#//guava/Graph">
      <eTypeParameters name="N"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImmutableGraph" instanceClassName="com.google.common.graph.ImmutableGraph"
        abstract="true" interface="true" eSuperTypes="#//guava/AbstractGraph">
      <eTypeParameters name="N"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MutableGraph" instanceClassName="com.google.common.graph.MutableGraph"
        abstract="true" interface="true" eSuperTypes="#//guava/Graph">
      <eTypeParameters name="N"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PredecessorsFunction" instanceClassName="com.google.common.graph.PredecessorsFunction"
        abstract="true" interface="true">
      <eTypeParameters name="N"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Network" instanceClassName="com.google.common.graph.Network"
        abstract="true" interface="true">
      <eTypeParameters name="N"/>
      <eTypeParameters name="E"/>
      <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eGenericSuperTypes eClassifier="#//guava/PredecessorsFunction">
        <eTypeArguments eTypeParameter="#//guava/Network/N"/>
      </eGenericSuperTypes>
      <eGenericSuperTypes eClassifier="#//guava/SuccessorsFunction">
        <eTypeArguments eTypeParameter="#//guava/Network/N"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MutableNetwork" instanceClassName="com.google.common.graph.MutableNetwork"
        abstract="true" interface="true">
      <eTypeParameters name="N"/>
      <eTypeParameters name="E"/>
      <eGenericSuperTypes eClassifier="#//guava/Network">
        <eTypeArguments eTypeParameter="#//guava/MutableNetwork/N"/>
        <eTypeArguments eTypeParameter="#//guava/MutableNetwork/E"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractNetwork" instanceClassName="com.google.common.graph.AbstractNetwork"
        abstract="true" interface="true">
      <eTypeParameters name="N"/>
      <eTypeParameters name="E"/>
      <eGenericSuperTypes eClassifier="#//guava/Network">
        <eTypeArguments eTypeParameter="#//guava/AbstractNetwork/N"/>
        <eTypeArguments eTypeParameter="#//guava/AbstractNetwork/E"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImmutableNetwork" instanceClassName="com.google.common.graph.ImmutableNetwork"
        abstract="true" interface="true">
      <eTypeParameters name="N"/>
      <eTypeParameters name="E"/>
      <eGenericSuperTypes eClassifier="#//guava/AbstractNetwork">
        <eTypeArguments eTypeParameter="#//guava/ImmutableNetwork/N"/>
        <eTypeArguments eTypeParameter="#//guava/ImmutableNetwork/E"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SuccessorsFunction" instanceClassName="com.google.common.graph.SuccessorsFunction"
        abstract="true" interface="true">
      <eTypeParameters name="N"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
