<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="execution" nsURI="http://de.tu-ilmenau/e4sm/execution/1.0.0"
    nsPrefix="execution">
  <eAnnotations source="http://www.eclipse.org/edapt">
    <details key="historyURI" value="e4sm.history"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode" eSuperTypes="#//ConnectableNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode" eSuperTypes="#//ConnectableNode #//DelayableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ConnectableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="2"
        upperBound="-1" eType="#//ConnectableNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeNode" eSuperTypes="#//ConnectableNode #//DelayableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="2"
        upperBound="-1" eType="#//ConnectableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ConnectableNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" eSuperTypes="#//ExecutionElement #//DelayableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ConnectableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ConnectableNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectableNode" abstract="true" interface="true"
      eSuperTypes="#//ExecutionElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Execution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ExecutionElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowFinal" eSuperTypes="#//ConnectableNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ConnectableNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//ExecutionElement">
    <eOperations name="getTangibleChild" eType="#//Expression"/>
    <eOperations name="getActualParent" eType="#//ExecutionElement"/>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="#//Expression">
    <eOperations name="isRealOperation" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="getActualParent" eType="#//ExecutionElement"/>
    <eOperations name="getTangibleChild" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//BinaryExpression">
    <eOperations name="isRealOperation" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addition" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtraction" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//BinaryExpression">
    <eOperations name="isRealOperation" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplication" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="division" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//AssignableElement #//ReferenceableItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Const" eSuperTypes="#//ReferenceableItem">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A const element can be assigned only once upon its initialization"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Expression">
    <eOperations name="getActualParent" eType="#//ExecutionElement"/>
    <eOperations name="getTangibleChild" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//ReferenceableItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeFunction">
    <eOperations name="getString" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="#//TimeFunctions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="par1" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="par2" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeFunctions">
    <eLiterals name="Det"/>
    <eLiterals name="Exp" value="1"/>
    <eLiterals name="Uni" value="2"/>
    <eLiterals name="DUni" value="3"/>
    <eLiterals name="Norm" value="4"/>
    <eLiterals name="LogNorm" value="5"/>
    <eLiterals name="Wei" value="6"/>
    <eLiterals name="Triang" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayableElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeFunction" eType="#//TimeFunction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment" eSuperTypes="#//ExecutionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AssignableElementReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignableElementReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//AssignableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignableElement" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceableItem" abstract="true" interface="true"
      eSuperTypes="#//ExecutionElement core.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPinReference" eSuperTypes="#//Expression">
    <eOperations name="getActualParent" eType="#//ExecutionElement"/>
    <eOperations name="getTangibleChild" eType="#//Expression"/>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPin" lowerBound="1"
        eType="ecore:EClass e4sm.ecore#//InputPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPinAttributeReference" eSuperTypes="#//InputPinReference">
    <eOperations name="getActualParent" eType="#//ExecutionElement"/>
    <eOperations name="getTangibleChild" eType="#//Expression"/>
    <eOperations name="toString" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="ecore:EClass core.ecore#//AttributeSpecification"/>
  </eClassifiers>
</ecore:EPackage>
