<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="guava" nsURI="https://guava.dev/releases/30.1" nsPrefix="guava">
  <eClassifiers xsi:type="ecore:EClass" name="Graph" instanceClassName="com.google.common.graph.Graph"
      abstract="true" interface="true">
    <eTypeParameters name="N"/>
    <eOperations name="isDirected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="inDegree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="node">
        <eGenericType eTypeParameter="#//Graph/N"/>
      </eParameters>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="allowsSelfLoops" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//PredecessorsFunction">
      <eTypeArguments eTypeParameter="#//Graph/N"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//SuccessorsFunction">
      <eTypeArguments eTypeParameter="#//Graph/N"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractGraph" instanceClassName="com.google.common.graph.AbstractGraph"
      abstract="true" interface="true" eSuperTypes="#//Graph">
    <eTypeParameters name="N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImmutableGraph" instanceClassName="com.google.common.graph.ImmutableGraph"
      abstract="true" interface="true" eSuperTypes="#//AbstractGraph">
    <eTypeParameters name="N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MutableGraph" instanceClassName="com.google.common.graph.MutableGraph"
      abstract="true" interface="true" eSuperTypes="#//Graph">
    <eTypeParameters name="N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredecessorsFunction" instanceClassName="com.google.common.graph.PredecessorsFunction"
      abstract="true" interface="true">
    <eTypeParameters name="N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" instanceClassName="com.google.common.graph.Network"
      abstract="true" interface="true">
    <eTypeParameters name="N"/>
    <eTypeParameters name="E"/>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eGenericSuperTypes eClassifier="#//PredecessorsFunction">
      <eTypeArguments eTypeParameter="#//Network/N"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//SuccessorsFunction">
      <eTypeArguments eTypeParameter="#//Network/N"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MutableNetwork" instanceClassName="com.google.common.graph.MutableNetwork"
      abstract="true" interface="true">
    <eTypeParameters name="N"/>
    <eTypeParameters name="E"/>
    <eGenericSuperTypes eClassifier="#//Network">
      <eTypeArguments eTypeParameter="#//MutableNetwork/N"/>
      <eTypeArguments eTypeParameter="#//MutableNetwork/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNetwork" instanceClassName="com.google.common.graph.AbstractNetwork"
      abstract="true" interface="true">
    <eTypeParameters name="N"/>
    <eTypeParameters name="E"/>
    <eGenericSuperTypes eClassifier="#//Network">
      <eTypeArguments eTypeParameter="#//AbstractNetwork/N"/>
      <eTypeArguments eTypeParameter="#//AbstractNetwork/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImmutableNetwork" instanceClassName="com.google.common.graph.ImmutableNetwork"
      abstract="true" interface="true">
    <eTypeParameters name="N"/>
    <eTypeParameters name="E"/>
    <eGenericSuperTypes eClassifier="#//AbstractNetwork">
      <eTypeArguments eTypeParameter="#//ImmutableNetwork/N"/>
      <eTypeArguments eTypeParameter="#//ImmutableNetwork/E"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuccessorsFunction" instanceClassName="com.google.common.graph.SuccessorsFunction"
      abstract="true" interface="true">
    <eTypeParameters name="N"/>
  </eClassifiers>
</ecore:EPackage>
