/*
 * generated by Xtext 2.27.0
 */
package abcd.xy.metamodel.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractABcdValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://de.tu-ilmenau/abcd/1.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://de.tu-ilmenau/abcd/core/1.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/emf/2002/Ecore"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://de.tu-ilmenau/abcd/analysis/1.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://de.tu-ilmenau/abcd/execution/1.0.0"));
		return result;
	}
}
