/*
 * generated by Xtext 2.27.0
 */
package abcd.xy.metamodel.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractABcdScopeProvider extends DelegatingScopeProvider {
}
