/************************************************************

	Transition_Canny__execution.cpp  -  generated by CodeGenerator r$Rev$

************************************************************/

#include "Transition_Canny__execution.h"

#include "MeasureObj_Execution__thread__pool__in__use.h"

Transition_Canny__execution::Transition_Canny__execution(int uniqueid, const char* name, NetClass* net, PlaceIdentMap places, string pagePath, double firingWeight, int priority, bool exp, bool takeFirst, bool isInfinite, bool hasLocalGuard) :
	Transition(uniqueid, name, net, places, pagePath, firingWeight, priority, exp, takeFirst, isInfinite, hasLocalGuard)
,
	x_Place ( *(net->getPlace( &places, "Canny_main"))),
	nona1_Place ( *(net->getPlace( &places, "Canny_executed")))
{
}

Transition_Canny__execution::~Transition_Canny__execution()
{
}

bool Transition_Canny__execution::globalGuard()
{
	return true;
}
void Transition_Canny__execution::initGlobalGuards()
{
}

void Transition_Canny__execution::moveTokens(TokenList &binding)
{
	TokenList::iterator binding_it = binding.begin();

	SMARTPTR(Token_Data) token_x = UPCAST_MACRO(Token_Data)(*binding_it ++);
	x_Place.removeToken(token_x);

	{
		// Handle token 1 of 1

		// Transfering Token: 1'x
		{
			nona1_Place.addToken(token_x);
		}
	}
}

TempBindingList* Transition_Canny__execution::generateBindingList()
{
	TokenList* tok;
	TempBindingList* tempBindings =  new TempBindingList();

	const TokenList &x_tokenList = getPlaceMarking(x_Place);
	TokenList::const_iterator x_iterator;

	for (x_iterator=x_tokenList.begin(); x_iterator!=x_tokenList.end(); ++x_iterator) {
		SMARTPTR(Token_Data) token_x = UPCAST_MACRO(Token_Data)(*x_iterator);
		
		// Check nulls 
		if (token_x == 0) {
			continue;
		}
		
		{
			
			// Check nulls 
			
		}

		// All local guards passed:
		tok = new TokenList();
		tok->push_back(UPCAST_MACRO(Token_Data)(*x_iterator));
		tempBindings->push_back(tok);
		return tempBindings;
	}
	return tempBindings;
}

void Transition_Canny__execution::log(TokenList &binding)
{
}

double Transition_Canny__execution::display(TokenList &binding)
{
	return 0.0;
}

Seconds_T Transition_Canny__execution::getFiringDelay(TokenList &binding) const
{
	// Orig Expression: Det( (  ( -1.5366062230611508+ ( 7.133349248009131E-6* ( 1280.0*1024.0 )  )  ) + ( 0.37520054070705516*3.0 )  ) )
	// C++  Expression:  (  ( -1.5366062230611508+ ( 7.133349248009131E-6* ( 1280.0*1024.0 )  )  ) + ( 0.37520054070705516*3.0 )  ) 

	TokenList::iterator binding_it = binding.begin();

	SMARTPTR(Token_Data) token_x = UPCAST_MACRO(Token_Data)(*binding_it ++);
	return delay.Det( (  ( -1.5366062230611508+ ( 7.133349248009131E-6* ( 1280.0*1024.0 )  )  ) + ( 0.37520054070705516*3.0 )  ) );
}

bool Transition_Canny__execution::hasTimeguard() const
{
	return false;
}

Seconds_T Transition_Canny__execution::Timeguard(const DateTime& now)
{
	return 0.0;
}

